Spice/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET Admin/Category/Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categories = await _context.Categories.ToListAsync();

            return View(categories);
        }

        // GET Admin/Category/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST Admin/Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category model)
        {
            if (!ModelState.IsValid) return View(model);

            await _context.Categories.AddAsync(model);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET Admin/Category/Details/{id}
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return BadRequest();

            var category = await _context.Categories.FindAsync(id);
            if (category == null) return NotFound();

            return View(category);
        }


        // GET Admin/Category/Edit/{id}
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return BadRequest();

            var category = await _context.Categories.FindAsync(id);
            if (category == null) return NotFound();

            return View(category);
        }

        // POST Admin/Category/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category model)
        {
            if (!ModelState.IsValid) return View(model);

            var categoryFromDb = await _context.Categories.FindAsync(model.CategoryId);
            if (categoryFromDb == null) return BadRequest();

            categoryFromDb.Name = model.Name;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET Admin/Category/Delete/{id}
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            var category = await _context.Categories.FindAsync(id);
            if (category == null) return NotFound();

            return View(category);
        }

        // POST Admin/Category/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            var categoryFromDb = await _context.Categories.FindAsync(id);
            if (categoryFromDb == null) return BadRequest();

            _context.Categories.Remove(categoryFromDb);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Spice/Areas/Admin/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubcategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SubcategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var subcategories = await _context.Subcategories.Include(s => s.Category).ToListAsync();
            return View(subcategories);
        }
    }
}

Spice/Views/Shared/_CreateAndBackButtonsPartial.cshtml
<div class="row">
    <div class="col-sm-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-sm-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Create New</a>

Spice/Views/Shared/_DeleteAndBackButtonsPartial.cshtml
@model int

<div class="row">
    <div class="col-sm-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-sm-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_DetailsEditAndBackButtonsPartial.cshtml
@model int

<div class="row">
    <div class="col-sm-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Edit</a>
    </div>
    <div class="col-sm-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_EditAndBackButtonsPartial.cshtml
@model int

<div class="row">
    <div class="col-sm-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-sm-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu" aria-labelledby="navbar-dropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Subcategory" asp-action="Index">Subcategory</a>
                                <a class="dropdown-item">Menu Item</a>
                                <a class="dropdown-item">Coupons</a>
                                <a class="dropdown-item">Users</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40;">
        <div class="container">
            &copy; 2019 - Spice
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/dbc78280f3.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_TableButtonsPartial.cshtml
@model int

<td style="width: 150px;">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Details" asp-route-id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Edit" asp-route-id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>